


alias p="sudo pacman --color=always"
alias pacman="pacman --color=always"
alias yay="yay --color=always"
alias vim="nvim"
alias config="/usr/bin/git --git-dir=$HOME/git/dotfiles-linux/ --work-tree=$HOME"
